import { observer } from 'mobx-react';
import Head from 'next/head';

import { useStores } from '../stores';

const AuthPage = observer(function () {
  const { hiroUserStore } = useStores();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex space-x-2 justify-center m-2">
        <button
          type="button"
          className="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
          onClick={() => hiroUserStore.authenticate()}
        >
          Authenticate
        </button>
      </div>
      <div className="space-x-2 justify-center">
        <pre className="bg-gray-800 text-gray-100 rounded-lg p-4 overflow-scroll">
          <code className="font-mono text-base">
            {hiroUserStore.user
              ? JSON.stringify(hiroUserStore.user, null, 2)
              : null}
          </code>
        </pre>
      </div>
    </>
  );
});

export default AuthPage;
