import { observer } from 'mobx-react-lite';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Game } from '../components/game/Game';
import { demoScenario } from '../models/demo';
import { GameState } from '../models/game';
import { useStores } from '../stores';

const Home = observer(() => {
  const { gameStore } = useStores();

  // const [scenario, setScenario] = useState(false);
  // useEffect(() => {
  //   if (scenario) return
  //   setScenario(true);

  //   setTimeout(() => {
  //     if (!scenario) {
  //       demoScenario(gameStore);
  //     }
  //   }, 500);

  //   return () => gameStore.reset();
  // }, [scenario]);

  let state = JSON.parse(JSON.stringify(gameStore));

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fixed inset-0">
        <Game {...state} />
      </div>

      <div className="absolute left-0 top-0 p-10 bg-gray">
          <button
            className="bg-white text-black rounded-full p-2"
            onClick={() => {
              console.log('test')
              gameStore.reset();
              demoScenario(gameStore);
            }}
          >
            Demo
          </button>
        </div>
    </div>
  );
});

export default Home;
