name: Docker build

on:
  release:
    types:
      - published

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install doctl and Authorize to Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to registry
        run: doctl registry login --expiry-seconds 3600

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, cache and push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.digitalocean.com/tookey/${{ github.event.repository.name }}:${{ github.event.release.tag_name }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
